#!/bin/bash

# .NET 10 Web API Project Generator
# Creates a new ASP.NET Core Web API project with best practices
#
# Usage:
#   ./new_api.sh <project_name> [output_directory]
#
# Examples:
#   ./new_api.sh MyApi
#   ./new_api.sh MyApi ./projects

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_NAME="$1"
OUTPUT_DIR="${2:-.}"

# Validate arguments
if [ -z "$PROJECT_NAME" ]; then
    echo -e "${RED}Error: Project name is required${NC}"
    echo "Usage: $0 <project_name> [output_directory]"
    echo ""
    echo "Examples:"
    echo "  $0 MyApi"
    echo "  $0 MyApi ./projects"
    exit 1
fi

# Check if dotnet CLI is available
if ! command -v dotnet &> /dev/null; then
    echo -e "${RED}Error: dotnet CLI not found${NC}"
    echo "Please install .NET 10 SDK from https://dotnet.microsoft.com/download/dotnet/10.0"
    exit 1
fi

# Check .NET version
echo -e "${BLUE}Checking .NET version...${NC}"
DOTNET_VERSION=$(dotnet --version)
echo -e "${GREEN}Found .NET SDK version: $DOTNET_VERSION${NC}"
echo ""

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Create solution directory
SOLUTION_DIR="$OUTPUT_DIR/$PROJECT_NAME"
if [ -d "$SOLUTION_DIR" ]; then
    echo -e "${RED}Error: Directory $SOLUTION_DIR already exists${NC}"
    exit 1
fi

echo -e "${BLUE}Creating .NET 10 Web API project: $PROJECT_NAME${NC}"
echo ""

# Create solution
cd "$OUTPUT_DIR"
dotnet new sln -n "$PROJECT_NAME"

# Create API project with minimal API template
dotnet new webapi -n "$PROJECT_NAME.Api" -o "$PROJECT_NAME/$PROJECT_NAME.Api" --use-controllers

# Create test project
dotnet new xunit -n "$PROJECT_NAME.Tests" -o "$PROJECT_NAME/$PROJECT_NAME.Tests"

# Add projects to solution
cd "$PROJECT_NAME"
dotnet sln add "$PROJECT_NAME.Api/$PROJECT_NAME.Api.csproj"
dotnet sln add "$PROJECT_NAME.Tests/$PROJECT_NAME.Tests.csproj"

# Add test reference to API project
cd "$PROJECT_NAME.Tests"
dotnet add reference "../$PROJECT_NAME.Api/$PROJECT_NAME.Api.csproj"

# Add common test packages
echo -e "${BLUE}Adding test dependencies...${NC}"
dotnet add package Microsoft.AspNetCore.Mvc.Testing
dotnet add package FluentAssertions
cd ..

# Create common folders
mkdir -p "$PROJECT_NAME.Api/Models"
mkdir -p "$PROJECT_NAME.Api/Services"
mkdir -p "$PROJECT_NAME.Api/Data"

# Create .gitignore
cat > .gitignore << 'EOF'
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Bb]in/
[Oo]bj/
[Ll]og/

# Visual Studio cache/options directory
.vs/

# Visual Studio Code
.vscode/

# JetBrains Rider
.idea/
*.sln.iml

# .NET
project.lock.json
project.fragment.lock.json
artifacts/

# NuGet Packages
*.nupkg
*.snupkg
**/packages/*

# Others
appsettings.Development.json
appsettings.*.json
!appsettings.json
EOF

echo ""
echo -e "${GREEN}✓ Project created successfully!${NC}"
echo ""
echo -e "${BLUE}Project structure:${NC}"
tree -L 2 "$PROJECT_NAME" 2>/dev/null || find "$PROJECT_NAME" -maxdepth 2 -type d
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  cd $PROJECT_NAME"
echo "  dotnet build"
echo "  dotnet run --project $PROJECT_NAME.Api"
echo ""
echo -e "${BLUE}Run tests:${NC}"
echo "  dotnet test"
echo ""
